import './globals.css'
import './globals_bk.css'
import ReactDOM from 'react-dom'
import Script from 'next/script'

export const metadata = {
  title: 'Launch Your Dev Career With Project-Based Coaching - JavaScript Mastery',
  description: 'Generated by create next app',
  charSet: 'utf-8',
  themeColor: '#000000'
}

export default function RootLayout({ children }) {
  ReactDOM.preload('./common.css', { as: "style" })
  return (
    <html lang="en">
      <body style={{overflow: 'auto'}}>{children}</body>
    </html>
  )
}
